python run_controls.py --arm A3 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --n_clauses_per_action 20 --seed 42 --save_rules --tag s42
python run_controls.py --arm A3 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --n_clauses_per_action 20 --seed 43 --save_rules --tag s43
python run_controls.py --arm A3 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --n_clauses_per_action 20 --seed 44 --save_rules --tag s44
python run_controls.py --arm A4 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --n_clauses_per_action 20 --seed 43 --save_rules --tag s43
python run_controls.py --arm A4 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --n_clauses_per_action 20 --seed 44 --save_rules --tag s44
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0 --seed 42 --tag ccp0.0_s42
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0 --seed 43 --tag ccp0.0_s43
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0 --seed 44 --tag ccp0.0_s44
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0001 --seed 42 --tag ccp0.0001_s42
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0001 --seed 43 --tag ccp0.0001_s43
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0001 --seed 44 --tag ccp0.0001_s44
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0003 --seed 42 --tag ccp0.0003_s42
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0003 --seed 43 --tag ccp0.0003_s43
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.0003 --seed 44 --tag ccp0.0003_s44
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.001 --seed 42 --tag ccp0.001_s42
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.001 --seed 43 --tag ccp0.001_s43
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.001 --seed 44 --tag ccp0.001_s44
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.003 --seed 42 --tag ccp0.003_s42
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.003 --seed 43 --tag ccp0.003_s43
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.003 --seed 44 --tag ccp0.003_s44
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.01 --seed 42 --tag ccp0.01_s42
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.01 --seed 43 --tag ccp0.01_s43
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.01 --seed 44 --tag ccp0.01_s44
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.03 --seed 42 --tag ccp0.03_s42
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.03 --seed 43 --tag ccp0.03_s43
python run_controls.py --arm A1 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --ccp_alpha 0.03 --seed 44 --tag ccp0.03_s44
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.003 --seed 42 --tag C0.003_s42
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.003 --seed 43 --tag C0.003_s43
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.003 --seed 44 --tag C0.003_s44
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.01 --seed 42 --tag C0.01_s42
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.01 --seed 43 --tag C0.01_s43
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.01 --seed 44 --tag C0.01_s44
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.03 --seed 42 --tag C0.03_s42
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.03 --seed 43 --tag C0.03_s43
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.03 --seed 44 --tag C0.03_s44
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.1 --seed 42 --tag C0.1_s42
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.1 --seed 43 --tag C0.1_s43
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.1 --seed 44 --tag C0.1_s44
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.3 --seed 42 --tag C0.3_s42
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.3 --seed 43 --tag C0.3_s43
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 0.3 --seed 44 --tag C0.3_s44
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 1.0 --seed 42 --tag C1.0_s42
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 1.0 --seed 43 --tag C1.0_s43
python run_controls.py --arm A2 --env_name MiniGrid-DoorKey-6x6-v0    --features_path ./stage1_outputs_doorkey/collected_data.pt    --stage1_path ./stage1_outputs_doorkey/stage1_outputs.pt    --hidden_dim 300 --k 50 --episodes 0 --out results/controls --C 1.0 --seed 44 --tag C1.0_s44
