python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 15 --dnf_epochs 600 --bimodal_ramp 120 --entropy_weight 0.015 --save_rules --tag doorkey_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 15 --dnf_epochs 600 --bimodal_ramp 120 --entropy_weight 0.015 --save_rules --tag doorkey_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag doorkey_ccp0.0_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag doorkey_ccp0.0001_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag doorkey_ccp0.0003_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag doorkey_ccp0.001_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag doorkey_ccp0.003_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag doorkey_ccp0.01_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag doorkey_ccp0.03_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag doorkey_C0.003_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag doorkey_C0.01_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag doorkey_C0.03_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag doorkey_C0.1_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag doorkey_C0.3_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_42 --hidden_dim 300 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag doorkey_C1.0_s42
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 15 --dnf_epochs 600 --bimodal_ramp 120 --entropy_weight 0.015 --save_rules --tag doorkey_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 15 --dnf_epochs 600 --bimodal_ramp 120 --entropy_weight 0.015 --save_rules --tag doorkey_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag doorkey_ccp0.0_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag doorkey_ccp0.0001_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag doorkey_ccp0.0003_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag doorkey_ccp0.001_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag doorkey_ccp0.003_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag doorkey_ccp0.01_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag doorkey_ccp0.03_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag doorkey_C0.003_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag doorkey_C0.01_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag doorkey_C0.03_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag doorkey_C0.1_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag doorkey_C0.3_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_43 --hidden_dim 300 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag doorkey_C1.0_s43
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 15 --dnf_epochs 600 --bimodal_ramp 120 --entropy_weight 0.015 --save_rules --tag doorkey_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 15 --dnf_epochs 600 --bimodal_ramp 120 --entropy_weight 0.015 --save_rules --tag doorkey_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag doorkey_ccp0.0_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag doorkey_ccp0.0001_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag doorkey_ccp0.0003_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag doorkey_ccp0.001_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag doorkey_ccp0.003_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag doorkey_ccp0.01_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag doorkey_ccp0.03_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag doorkey_C0.003_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag doorkey_C0.01_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag doorkey_C0.03_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag doorkey_C0.1_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag doorkey_C0.3_s44
python run_controls.py --env_name MiniGrid-DoorKey-6x6-v0 --lucid_split_dir outputs/lucid_model_doorkey_44 --hidden_dim 300 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag doorkey_C1.0_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 300 --bimodal_ramp 60 --entropy_weight 0.075 --save_rules --tag dyobs_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 300 --bimodal_ramp 60 --entropy_weight 0.075 --save_rules --tag dyobs_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag dyobs_ccp0.0_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag dyobs_ccp0.0001_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag dyobs_ccp0.0003_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag dyobs_ccp0.001_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag dyobs_ccp0.003_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag dyobs_ccp0.01_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag dyobs_ccp0.03_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag dyobs_C0.003_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag dyobs_C0.01_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag dyobs_C0.03_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag dyobs_C0.1_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag dyobs_C0.3_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_42 --hidden_dim 200 --k 20 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag dyobs_C1.0_s42
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 300 --bimodal_ramp 60 --entropy_weight 0.0 --save_rules --tag dyobs_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 300 --bimodal_ramp 60 --entropy_weight 0.0 --save_rules --tag dyobs_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag dyobs_ccp0.0_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag dyobs_ccp0.0001_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag dyobs_ccp0.0003_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag dyobs_ccp0.001_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag dyobs_ccp0.003_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag dyobs_ccp0.01_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag dyobs_ccp0.03_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag dyobs_C0.003_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag dyobs_C0.01_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag dyobs_C0.03_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag dyobs_C0.1_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag dyobs_C0.3_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_43 --hidden_dim 200 --k 20 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag dyobs_C1.0_s43
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 300 --bimodal_ramp 60 --entropy_weight 0.0 --save_rules --tag dyobs_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 300 --bimodal_ramp 60 --entropy_weight 0.0 --save_rules --tag dyobs_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag dyobs_ccp0.0_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag dyobs_ccp0.0001_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag dyobs_ccp0.0003_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag dyobs_ccp0.001_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag dyobs_ccp0.003_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag dyobs_ccp0.01_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag dyobs_ccp0.03_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag dyobs_C0.003_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag dyobs_C0.01_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag dyobs_C0.03_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag dyobs_C0.1_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag dyobs_C0.3_s44
python run_controls.py --env_name MiniGrid-Dynamic-Obstacles-5x5-v0 --lucid_split_dir outputs/lucid_model_dyobs_44 --hidden_dim 200 --k 20 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag dyobs_C1.0_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 20 --dnf_epochs 900 --bimodal_ramp 200 --entropy_weight 0.005 --save_rules --tag cartpole_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 20 --dnf_epochs 900 --bimodal_ramp 200 --entropy_weight 0.005 --save_rules --tag cartpole_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag cartpole_ccp0.0_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag cartpole_ccp0.0001_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag cartpole_ccp0.0003_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag cartpole_ccp0.001_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag cartpole_ccp0.003_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag cartpole_ccp0.01_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag cartpole_ccp0.03_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag cartpole_C0.003_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag cartpole_C0.01_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag cartpole_C0.03_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag cartpole_C0.1_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag cartpole_C0.3_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag cartpole_C1.0_s42
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 20 --dnf_epochs 900 --bimodal_ramp 200 --entropy_weight 0.005 --save_rules --tag cartpole_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 20 --dnf_epochs 900 --bimodal_ramp 200 --entropy_weight 0.005 --save_rules --tag cartpole_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag cartpole_ccp0.0_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag cartpole_ccp0.0001_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag cartpole_ccp0.0003_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag cartpole_ccp0.001_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag cartpole_ccp0.003_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag cartpole_ccp0.01_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag cartpole_ccp0.03_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag cartpole_C0.003_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag cartpole_C0.01_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag cartpole_C0.03_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag cartpole_C0.1_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag cartpole_C0.3_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag cartpole_C1.0_s43
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 20 --dnf_epochs 900 --bimodal_ramp 200 --entropy_weight 0.005 --save_rules --tag cartpole_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 20 --dnf_epochs 900 --bimodal_ramp 200 --entropy_weight 0.005 --save_rules --tag cartpole_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag cartpole_ccp0.0_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag cartpole_ccp0.0001_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag cartpole_ccp0.0003_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag cartpole_ccp0.001_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag cartpole_ccp0.003_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag cartpole_ccp0.01_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag cartpole_ccp0.03_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag cartpole_C0.003_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag cartpole_C0.01_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag cartpole_C0.03_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag cartpole_C0.1_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag cartpole_C0.3_s44
python run_controls.py --env_name PixelCartPole-v1 --lucid_split_dir outputs/lucid_model_cartpole_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag cartpole_C1.0_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag pong_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag pong_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag pong_ccp0.0_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag pong_ccp0.0001_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag pong_ccp0.0003_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag pong_ccp0.001_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag pong_ccp0.003_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag pong_ccp0.01_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag pong_ccp0.03_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag pong_C0.003_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag pong_C0.01_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag pong_C0.03_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag pong_C0.1_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag pong_C0.3_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag pong_C1.0_s42
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag pong_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag pong_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag pong_ccp0.0_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag pong_ccp0.0001_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag pong_ccp0.0003_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag pong_ccp0.001_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag pong_ccp0.003_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag pong_ccp0.01_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag pong_ccp0.03_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag pong_C0.003_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag pong_C0.01_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag pong_C0.03_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag pong_C0.1_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag pong_C0.3_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag pong_C1.0_s43
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag pong_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag pong_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag pong_ccp0.0_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag pong_ccp0.0001_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag pong_ccp0.0003_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag pong_ccp0.001_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag pong_ccp0.003_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag pong_ccp0.01_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag pong_ccp0.03_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag pong_C0.003_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag pong_C0.01_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag pong_C0.03_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag pong_C0.1_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag pong_C0.3_s44
python run_controls.py --env_name PongNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_pong_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag pong_C1.0_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag boxing_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag boxing_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag boxing_ccp0.0_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag boxing_ccp0.0001_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag boxing_ccp0.0003_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag boxing_ccp0.001_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag boxing_ccp0.003_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag boxing_ccp0.01_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag boxing_ccp0.03_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag boxing_C0.003_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag boxing_C0.01_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag boxing_C0.03_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag boxing_C0.1_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag boxing_C0.3_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_42 --hidden_dim 512 --k 50 --seed 42 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag boxing_C1.0_s42
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag boxing_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag boxing_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag boxing_ccp0.0_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag boxing_ccp0.0001_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag boxing_ccp0.0003_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag boxing_ccp0.001_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag boxing_ccp0.003_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag boxing_ccp0.01_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag boxing_ccp0.03_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag boxing_C0.003_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag boxing_C0.01_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag boxing_C0.03_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag boxing_C0.1_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag boxing_C0.3_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_43 --hidden_dim 512 --k 50 --seed 43 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag boxing_C1.0_s43
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A3 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag boxing_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A4 --n_clauses_per_action 10 --dnf_epochs 600 --bimodal_ramp 200 --entropy_weight 0.3 --save_rules --tag boxing_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0 --tag boxing_ccp0.0_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0001 --tag boxing_ccp0.0001_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.0003 --tag boxing_ccp0.0003_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.001 --tag boxing_ccp0.001_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.003 --tag boxing_ccp0.003_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.01 --tag boxing_ccp0.01_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A1 --ccp_alpha 0.03 --tag boxing_ccp0.03_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.003 --tag boxing_C0.003_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.01 --tag boxing_C0.01_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.03 --tag boxing_C0.03_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.1 --tag boxing_C0.1_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 0.3 --tag boxing_C0.3_s44
python run_controls.py --env_name BoxingNoFrameskip-v4 --lucid_split_dir outputs/lucid_model_boxing_44 --hidden_dim 512 --k 50 --seed 44 --episodes 0 --out results/controls_same --arm A2 --C 1.0 --tag boxing_C1.0_s44
